name: Hourly Energy Prediction

on:
  schedule:
    - cron: '0 * * * *' # Runs at the start of every hour
  workflow_dispatch: # Allows you to run it manually for testing

permissions:
  contents: write  # This is the "Key" that lets the bot push the CSV

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas xgboost joblib requests holidays supabase 

      - name: Run prediction and save to Supabase
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python fetch_data.py

      - name: Check Model Health
        run: python retrain_trigger.py